name: Test
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        uses: actions/checkout@v3
        run: npm ci
      - name: Unit Tests
        run: npm run test -- --watch
      - name: E2E Tests
        uses: cypress-io/github-action@v4
        with:
          start: npm run start
          wait-on: http://localhost:3000